### ISSUE TITLE
Apparent bug while getting key item that is normally the Diamond

### ISSUE THREAD

**Issue by Ribbee** [stochaztic/bizarre_dimension#3]
Cleared out the mole caves, talked to the foreman and he said his thing about he'd get right back to work. Started walking back to Fourside, and when the party was stopped, his backhoe sprite was replaced by the guy in the red car. No text box popped up, and party just stayed frozen in spot looking at the car. Granted, it's a nice car, but not THAT nice. Music continued as normal, but did not respond to any button inputs. Had to reset.

**Comment by stochaztic** [comment]
Ah, yup. Out of curiosity, how long did you let it run? A group of bugs like this actually resolve after five minutes or so, as an npc is slowly walking across the entire map. 

In any event, this is actually a bug with NPC Sprite randomization (almost certainly occurs in normal game mode as well) and needs corrected.

**Comment by Ribbee** [comment]
I figured it was something to do with the sprite. Didn't leave it running too long, but will do so when I'm back in the area.

**Comment by Ribbee** [comment]
Yeah, that was it. Don't know exactly how long it took because I used fast forward, but it did at least 5 loops of the song. Would have got too impatient to wait for it on my own, so thanks for the fast response 👍
